### ISSUE TITLE
Inclusion request for Conan Center

### ISSUE THREAD

**Issue by danimtb** [vthiery/conan-statsd-client#4]
Related to vthiery/cpp-statsd-client#7

Hi @vthiery,

Finally got the time to review your inclusion request for this library, sorry for the delay.

First of all I'd like to point out that the best way to maintain the Conan recipe aligned with the version of the library will be to create a branch for each version. For example: `stable/0.0.4` or simply `0.0.5`. That way small changes for the recipe will update the package in Bintray and changing between branches will ensure the reproducibility  of the Conan package creation.

Some things I found while trying the Conan package:

Looks like the library is using some experimental features like #include <experimental/optional>. However, in Visual Studio 2017 the optional feature is available just under `#include <optional>`.

When trying to workaround this, I found `udpsender.hpp(4): fatal error C1083: Cannot open include file: 'arpa/inet.h'`, which obviously is not a Windows library and [Winshok API will be needed instead](https://stackoverflow.com/questions/20543940/where-do-i-get-arpa-inet-h).

So my conclusions are that this header only library is only intended for Unix users. If that is the case it will require to add an check in the `configure()` section of the conanfile.

Other things missing are the packaging of the library license and the addition of C++17 flags for test_package.

Please clarify the points above and I will be happy to contribute those changes to the repo!

Thanks a lot

**Comment by vthiery** [comment]
Hi @danimtb ! sorry for the delay

I released a new version of the library, requiring C++17 and removing the use of `experimental`. I started the corresponding package release [here](https://github.com/vthiery/conan-statsd-client/pull/5). 

The `configure()` function is still missing, could you please advise on what to do there exactly?

Thanks for the help!

**Comment by danimtb** [comment]
Hi! Changes in the PR look quite good.

For the configure method it would be just something like:

```
def configure(self):
    if self.settings.os == "Windows":
        raise Exception("This library only supports Unix like systems") # Use an appropriate message here
```

This will block the users trying to use this library on Windows.

Also make sure to point the PR to a new branch ``1.0.0``. That way we keep the recipe for ``5.0.0`` live in case it needs an update in the future.

Many thanks! 😄

**Comment by vthiery** [comment]
All done. Thanks for the help!

**Comment by danimtb** [comment]
Approved for Conan Center! Your library is now available from the conan center remote.
Thanks a lot! 😃

**Comment by vthiery** [comment]
Thanks @danimtb!
